#!/bin/bash

# This script will install webmin on Debian
# Please run it as root - 'sudo bash 03'

apt-get install ca-certificates -y

wget http://www.webmin.com/download/deb/webmin-current.deb

dpkg --install webmin-current.deb

rm webmin-current.deb

apt-get -f install -y
